name: advance_pdf_viewer
description: A flutter plugin for handling PDF files. Works on both Android & iOS
version: 1.2.2
homepage: https://github.com/lohanidamodar/pdf_viewer

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.0.0-nullsafety.1
  numberpicker: ^2.0.0
  path_provider: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: pt.tribeiro.flutter_plugin_pdf_viewer
        pluginClass: FlutterPluginPdfViewerPlugin
      ios:
        pluginClass: FlutterPluginPdfViewerPlugin
